export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENT = "INIT_INGREDIENT";
export const FETCH_INGREDIENTFAILURE = "FETCH_INGREDIENTFAILURE";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const INIT_INGREDIENT_INITIATE = "INIT_INGREDIENT_INITIATE";


export const PURCHASE_BURGER_INITIATE="PURCHASE_BURGER_INITIATE";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const ORDER_FETCH_INITIATE="ORDER_FETCH_INITIATE"
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";
export const ORDER_FETCH_START = "ORDER_FETCH_START";

export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_USER="AUTH_USER";
export const CHECK_EMAIL="CHECK_EMAIL";

export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";



export const SHOW_MAP="SHOW_MAP";
export const SAVE_MAP="SAVE_MAP";
export const CLOSE_MAP="CLOSE_MAP";